export const reviews = [
  {
    id: 1,
    header: "HELPED MY COMMUNITY",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/1eb5518f637671f34785d34d07a9d3f9/08a25e1b",
    text: `“ Volunteering is the ultimate exercise in democracy. You vote in elections once a year, but when you volunteer, you vote every day about the kind of community you want to live in. ”`,
    name: "― Dr Syed Muhammad Zeeshan",
    position: "Marketing Director",
  },
  {
    id: 2,
    header: "VERY INNOVATIVE",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/704324daed84a7ff774ad5a22a061ddf/dc44d808",
    text: `“ Volunteers are the only human beings on the face of the earth who reflect this worlds' compassion, unselfish caring, patience, and just plain loving one another. ”`,
    name: "― Erma Bombeck",
    position: "Chief Operating Officer",
  },
  {
    id: 3,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“You make a living by what you get. You make a life by what you give.”",
    name: "― Winston Churchill",
    position: "Business Owner",
  },
  {
    id: 4,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“You may not have saved a lot of money in your life, but if you have saved a lot of heartaches for other folks, you are pretty rich already.”",
    name: "― Seth Parker",
    position: "Business Owner",
  },
  {
    id: 5,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“The smallest act of kindness is worth more than the grandest intention.”",
    name: "― Oscar Wilde",
    position: "Business Owner",
  },
  {
    id: 6,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“Volunteers do not necessarily have the time; they just have the heart.”",
    name: "― Elizabeth Andrew",
    position: "Business Owner",
  },
  {
    id: 7,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“You can study government and politics in school, but the best way to really understand the process is to volunteer your time.”",
    name: "― Rob Mckena",
    position: "Business Owner",
  },
  {
    id: 8,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“Everybody can be great. Because anybody can serve. You don’t have to have a college degree to serve. You don’t have to make your subject and your verb agree to serve…. You don’t have to know the second theory of thermodynamics in physics to serve. You only need a heart full of grace. A soul generated by love.”",
    name: "― Martin Luther King",
    position: "Business Owner",
  },
  {
    id: 9,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“Wherever you turn, you can find someone who needs you. Even if it is a little thing, do something for which there is no pay but the privilege of doing it. Remember, you don’t live in the world all of your own.”",
    name: "― Albert Schweitzer",
    position: "Business Owner",
  },
  {
    id: 10,
    header: "HEALTH",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/9e7c735a19ac451b1338d7e4d2bda9b5/7f2b5fec",
    text: "“As you grow older, you will discover that you have two hands — one for helping yourself, the other for helping others.”",
    name: "― Audrey Hepburn",
    position: "Business Owner",
  },
];

export const photos = [
  // "https://v5.airtableusercontent.com/v1/4/4/1655942400000/QDFMjc_XjeeCsGmutpVy0Q/D4jg0S34Ohnqm2kq-VLqRKgvvnuMR--BSs2ht0MTcu3jybfVDhCO6_u7ZhOBzd3Z5AveKB-jG8-aTkxXgRowJg/ELI5CRKQ8HDgsWcY7puXPyw5hohLopnxTGGMQn2Yqk0",
  // "https://v5.airtableusercontent.com/v1/4/4/1655942400000/fwi09269FYgDh2Z_mtKCag/ZgXoag2RDkC1tCLW-mHqmc-38q5NthZI0PfrTPl1wNv8luVNZgODuvkPiiNxR3r78Bl9tNFeG6srnVzVgQuNpg/6EUPkfwdqgihlmLp_-PBt7lvREdBZeIbjzgHlnJF3KE",
  "https://dl.airtable.com/.attachmentThumbnails/d9866d1ac19e6708ed234664c9930021/8a9ffdd4",
  "https://dl.airtable.com/.attachmentThumbnails/51d799d6cd74842d5f715188f40c06fb/1cb24a13",
  "https://dl.airtable.com/.attachmentThumbnails/2e1d5ce4d20837668bb10626885bbd3f/a5cd9c09",
];
